### ISSUE TITLE
Discidia attunment not granting perk EXP on a MP server

### ISSUE THREAD

**Issue by SilventheThrid** [HellFirePvP/AstralSorcery#1040]
I attuned myself to the Discida  constellation, however I do not gain exp from dealing damage, either with Vanilla weapons or Modded ones. I tested in in a SP world and it works fine, and I tested Evorsio on the server and it functions as expected.

astralsorcery-1.12.2-1.10.11
forge 14.23.5.2807
spongeforge-1.12.2-2768-7.1.6-RC3596

Mod pack: Dungeon, Dragons and Space Shuttles: version 4.7b

Edit: forgot to include sponge version

**Comment by Doomgull** [comment]
Can you replicate using the same pack without sponge on a server instance?

Also, was this the first root perk you had taken?

**Comment by DishonoredRaven** [comment]
Having a similar issue to this on a SpongeForge server. Took the singularity perk with Vicio as my first root perk, then took Discidia and Evorsio in that order. Now I can only gain xp from breaking blocks, and only when Evorsio is my root perk.

Forge version: 2823 (The latest, as of the writing of this.)
SpongeForge: 3616
Astral Sorcery: 1.10.11 (Haven't updated to 1.10.12 yet)

**Comment by HellFirePvP** [comment]
Next version will include more logging options aswell to help try find out why exp are not awarded correctly.

**Comment by Doomgull** [comment]
@SilventheThrid @DishonoredRaven if you are running 1.10.13 or later, please enable the perk logging option for some debug outputs regarding xp gain with discidia and let us know.

**Comment by Brillik** [comment]
I encountered this same issue on FTB: Interactions today, on the OpenSkies multiplayer server. I'm not sure what version of spongeforge they are running if they are. I'm guessing its the server pack from the FTB website. I've asked their admin for advice and am awaiting a response.
Forge - 2836
Astral Sorcery 1.10.17
FTB:Interactions 1.5.0

**Comment by Doomgull** [comment]
There is a debug log config that can be enabled to display tracking of xp gain actions. Please use it so we have data.

**Comment by BransonD** [comment]
Hey, I'm the owner of Open Skies, we are currently running: 

Forge - 2836
spongeforge-1.12.2-2815-7.1.6-RC3616_with_treebeacon_hackery_and_jed_seed_fix (compiled by Phit)
Astral Sorcery 1.10.17

`Debug Log`
[https://gist.github.com/BransonD/ea673127cd00d38bba3699cfe8558029](url)

Removed all non-crucial and private information, but it seems as though any killing of both Spawned Mobs and Natural Mobs using Bow, Stone Sword, or Fist does not result in any XP being registered. We killed multiple vanilla zombies and zombies from Thaumcraft to no avail. The debug log registers me breaking stone blocks but not killing. I hope this helps you out.

If there is anything else I can do to help just let me know
@Doomgull

**Comment by HellFirePvP** [comment]
Hm, that sure is enlightening.

https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/constellation/perk/tree/root/DiscidiaRootPerk.java#L39

That's the code doing the discidia exp stuffs, so it doesn't even get to the point to actually grant exp. Does the pack have anything that modifiers the way damage is dealt?

**Comment by phit** [comment]
Can you guys with the issue run the sponge server with `-Dsponge.shouldFireAll=true` in your java arguments and please make an issue on the SpongeForge issue tracker, I wasn't even aware of this issue until a few minutes ago! If you don't report things like this, they can't get fixed.

**Comment by SSKirillSS** [comment]
Launched a local test server with parameters `java -jar -Xmx3G -Xms3G -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -Dsponge.shouldFireAll=true forge-1.12.2-14.23.5.2838-universal.jar --nogui`, but I did not found anything interesting or specific in the game and the console. experience still does not come.

**Comment by Doomgull** [comment]
Issue resolved with a sponge fix: https://github.com/SpongePowered/SpongeForge/commit/24b76b6dda7e4ac6f09986a34a495fd574dcf523

**Comment by zediious** [comment]
This issue is still occurring for me running SpongeForge 1.12.2-2838-7.3.0, was this fix applied before this version? The dates would have me assume so. This is occurring on a public SkyFactory 4 server running the aforementioned spongeforge version.

**Comment by PocketfulOfGeese** [comment]
You'd have to talk to Sponge about that, not AS.
