### ISSUE TITLE
Mantle of the Stars (vicio) not Working 

### ISSUE THREAD

**Issue by Titaniumlord430** [HellFirePvP/AstralSorcery#312]
Hello i have just made the mantle of the stars and attuned it to vicio , the journal says that it works like a elytra but when i jump using my staff attuned to vicio and press space i don't fly instead i go rapidly in and out of elytra mode really fast . do you know how i can fix this . Thanks a lot

**Comment by Titaniumlord430** [comment]
I have version 1.2.2 1.7  is that the newest version or does fixed next update mean it's gona get fixed in the next update . If so when should I expect it to come . Thanks a lot , I think your mod is really awesome .

**Comment by Doomgull** [comment]
Next update, no eta. If 1.7 is shown as latest on curse, and you're on that one, obv it isnt fixed yet.
