### ISSUE TITLE
Celestial Gateway star field doesn't appear

### ISSUE THREAD

**Issue by bsvdw** [HellFirePvP/AstralSorcery#529]
I'm playing FTB Revelation on LAN with my bro (I'm the host), and the celestial gateway doesn't work right. When I walk onto the platform, it doesn't begin to darken and when I stand on the gateway and look at the destination, my HUD disappears. I can still teleport and the particles appear, but I have to remember where my other gateways are. If I close out of the game entirely and reload the world, it does darken, but when I look at the gold star, my HUD and the stars disappear, and I'm back where I started. From watching other YouTubers, the same thing happens to them, but only for a brief moment, while it takes a screenshot. I feel like for me it tries to take a screenshot for the remnant image, but the stars never return. This happens in any world I create in that modpack. Can someone help?

**Comment by HellFirePvP** [comment]
Anything in the log while doing so?

**Comment by Doomgull** [comment]
Also, version of Forge, please?

**Comment by bsvdw** [comment]
I'm running (an unmodified) version 1.3.0 of the Official FTB Revelation Modpack. I haven't added any new mods to the modpack. I'm not sure what version of forge it is, and I don't know what spongeforge is. I've included the red text I saw in the log window. The first one I noticed on world startup, the second happened while walking towards the Gateway and during the teleport.
[Astral Sorcery Logs.txt](https://github.com/HellFirePvP/AstralSorcery/files/1670425/Astral.Sorcery.Logs.txt)

**Comment by bsvdw** [comment]
I've been informed by my bro that it works perfectly for him. I am not pleased with him. He is on the same world as me via LAN, and I'm the host. Is there anything I could try to fix my end of this?

**Comment by Doomgull** [comment]
That's an interesting looking one, if you delete the cache folder for the astral sorcery screenshots located inside the pack folder, does it change?

**Comment by bsvdw** [comment]
There are no screenshots in the C:\Users\[MyName]\Downloads\FTB\FTBRevelation\minecraft\astralsorcery\gatewayScreenshots\[WorldName] However, there are screenshots of the gates in C:\Users\[MyName]\Downloads\FTB\FTBRevelation\minecraft\screenshots I've also just updated to FTB Revelation Version 1.4.0 without any result. I'm trying the deleting folders thing now.

**Comment by Doomgull** [comment]
Move it out of your user folder. Executing things out of the windows user folder tends to result in a weird permissions denials sometimes. See if it still repeats if you relocate the entire Minecraft instance into somewhere like c:\temp.

**Comment by bsvdw** [comment]
I have moved the entire FTB Folder into c:\temp Now how do I launch my game? When I open the FTB application and click the launch button, it makes a new FTB folder and reinstalls the modpack

**Comment by Doomgull** [comment]
Gotta go into the launvher options and change the path for pack installation to match. The help file/page for the launcher you are using siuld contain that information.

**Comment by bsvdw** [comment]
Launching the game from c:\temp method and deleting folders method have come up with nothing. Although I have learned my forge version is 14.23.1.2601

**Comment by bsvdw** [comment]
[14:11:51] [main/INFO] [Astral Sorcery]: [AstralSorcery] Couldn't save screenshot for position: dimid=0, pos=BlockPos{x=519, y=67, z=-478} popped up in the log when I teleported just now. This was in white text, while everything else around it was red.

**Comment by HellFirePvP** [comment]
>_> full log please. as always.

**Comment by bsvdw** [comment]
http://paste.feed-the-beast.com/view/cf84c9bf

**Comment by HellFirePvP** [comment]
> [14:41:41] [main/INFO] [STDERR]: [com.sun.imageio.spi.FileImageOutputStreamSpi:createOutputStreamInstance:-1]: java.io.FileNotFoundException: C:\temp\FTB\FTBRevelation\minecraft\astralsorcery\gatewayScreenshots\if_she_breathes...\0\148;86;5.png (The system cannot find the path specified)

Well, seems like the filesystem doesn't support dots in names - who would've guessed. Thought i excluded them. Oh well.

**Comment by Pseudoreal** [comment]
I'm having the exact same issue. Was a fix found?

**Comment by Doomgull** [comment]
This was fixed 2.5 years ago in version 1.9. The fix was clearly found in the comment directly above yours.

**Comment by Pseudoreal** [comment]
Well I'm running AS 1.10.25 and this is still happening. After stepping on gateway my HUD disappears as well as the starscape. AS isn't creating any screenshots. I can't find any permission issues that would be stopping it. I do have a "..." as part of my world name. Is that why?

**Comment by Pseudoreal** [comment]
Removed the "..." from the end of my world name. Seems to be working fine now. Sorry, from the wording above it looked like that was something that was patched.
